### PR TITLE
Allows the current fn htmltopdf return buffer

### PR DESCRIPTION
**Pull request by CarlosLunaGit**
hello guys I have a Use case that i would like run by you, and if possible to get it merged.

basically i am planning into using this library to create a pdf file out of an XML data source using Handlebars templates, and return it as a buffer that can be downloaded from a client app when using our api endpoint.

So the change is pretty short, i have added 3 lines, but also another file with an example of its use case.

Greetings, and thanks for creating html_to_pdf :)

### CODE REVIEW

**Comment by chuongtrh** [comment]
@CarlosLunaGit  Could you remove folder .vs in the source code?

**Comment by CarlosLunaGit** [comment]
@chuongtrh  Sure, sorry for the late response should i go ahead and do remove the folder? or should we drop this PR?

**Comment by chuongtrh** [comment]
@CarlosLunaGit Pls remove the folder **.vs** and I will merge this PR

**Comment by CarlosLunaGit** [comment]
@chuongtrh done, thanks!

**Pull request merged**
